#!/usr/bin/env bash
# Sets up nginx

sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/' /etc/nginx/sites-available/default

sudo service nginx restart