#!/bin/bash

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom index.html
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

# # Ensure nginx is listening on port 80
# sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
# sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/' /etc/nginx/sites-available/default

# Restart nginx without using systemctl
sudo service nginx restart