#!/usr/bin/env bash
# Configure new nginx server, /redirect_me redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
new_path="server_name _;\n\trewrite ^\/redirect_me https://github.com/MohamDahALU permanent;"
sudo sed -i "s|server_name _;|$new_path|" /etc/nginx/sites-enabled/default

sudo service nginx restart